.travis.yml
This pull request (PR) pins the version of Python used by Travis for the build process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-it/refractr/12)
=> Pin Travis's Python version

refractr/validate.py, requirements.txt
- refractr script now has a dep on aiohttp, asyncio is there by default
- this speeds up processing 1:45 -> 9s on my machine
=> sped up validation web calls using asyncio+aiohttp

refractr/validate.py, tests/test_refractr.py
This is a smaller change after PR #41 lands.  It is a cleanup of all of the logic in validate.py
=> Cleanup validation logic

refractr/nginx/nginx.conf
Adding some richness to our NGINX logging
=> add host header and request time to nginx logging

refractr/nginx/conf.d/default.conf, refractr/nginx/nginx.conf
Adding some conditionals for user agent and URI path
=> Tuning some conditional nginx logging

prod-refractr.yml, prod-refractr.yml.bak
- discourse
- etherpad
- phonebook
- careers
=> added some more domains:

prod-refractr.yml
- [www.]firefoxparty.com
- [www.]mozillaparty.com
- survey.mozilla.com
- college.mozilla.{com,org}
- interns.mozilla.com
- university.mozilla.{com,org}
- apps.mozilla.com
- market.mozilla.org
- extranet.mozilla.org
- ux.firefox.com
- prs.paas.allizom.org
- whatsdeployed.paas.allizom.org
=> added more domains from apache conf

prod-refractr.yml
Original request https://jira.mozilla.com/browse/SE-1371
This redirects dxr.mozilla.org to searchfox.org
=> Redirect dxr.mozilla.org to searchfox.org

prod-refractr.yml
See https://jira.mozilla.com/browse/SE-1666
Checklist:
=> change ideas.m.o redirect to https://mozilla.github.io/imo-placeholder/

prod-refractr.yml
JIRA ticket: https://jira.mozilla.com/browse/SE-1856
=> redirect ideas.mozilla.org to mozilla.crowdicity.com

prod-refractr.yml
JIRA ticket: https://jira.mozilla.com/browse/SE-1224
=> add www. and staging. to inhumanads.com redirect

prod-refractr.yml
JIRA ticket: https://jira.mozilla.com/browse/SE-1571
=> redirect developer.cdn.mozilla.net to developer.mozilla.org

prod-refractr.yml
JIRA ticket: https://jira.mozilla.com/browse/SE-1677
=> redirect goggles.mozilla.org & thimble.mozilla.org to foundation.m.o pages

prod-refractr.yml
JIRA ticket: https://jira.mozilla.com/browse/SE-1627
=> Redirect surveillance.mozilla.org to foundation.mozilla.org.

prod-refractr.yml
JIRA ticket: https://jira.mozilla.com/browse/SE-1902
=> Redirect input.mozilla.org to ideas.mozilla.org (SE-1902).

prod-refractr.yml
- [ x] Have you updated the relevant YAML in the PR?
- [ x] Have you checked if there are any TLS cert concerns - e.g. if the domain being redirected already exists, and it is being changed to point at Refractr, is a temporary TLS 'outage' while waiting for Lets Encrypt certification via HTTP challenge okay? If not, [have you followed these steps for using DNS challenges with our cert-manager setup](https://mana.mozilla.org/wiki/display/SRE/Refractr+-+How+To+-+DNS+Challenges)?
=> Redirect for jira.mozilla.com to mozilla-hub.atlassian.net

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SE-2005
=> strip paths from input.m.o to ideas.m.o redirect

prod-refractr.yml
JIRA ticket: Came up in context of Let's Encrypt Cert Expiration Alerts
=> Pastebin recom kraken decom

prod-refractr.yml, refractr/complex.py
JIRA ticket: [https://mozilla-hub.atlassian.net/browse/SE-2241](SE-2241)
=> Add bugzil.la redirects.

prod-refractr.yml
=> Adding a staging domain

.github/workflows/publish.yml, SRE_INFO.md, docs/refractr-architecture.md, dodo.py, refractr/cfg.py, tf/main.tf, tf/outputs.tf, tf/state.tf
JIRA ticket: SE-2916
Replace AWS IAM user to AWS role in CI
Bonus: move the TF folder to [mozilla-it/itse-apps-prod-1-infra](https://github.com/mozilla-it/itse-apps-prod-1-infra)
=> Replace AWS IAM user to role in CI SE-2916

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SE-2698
=> Security wiki redirect to mana

prod-refractr.yml
JIRA ticket: branch copy of #222 to get some fixes in & run CI on for upstream fixes.
=> Update careers config to include paths

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SE-2950
=> add mozillaindia.org redirects

stage-refractr.yml
=> Added ftv stage redirect

prod-refractr.yml
Redirecting ideas.mozilla.com to ideas.mozilla.org
=> chore(ideas): Point ideas.mozilla.com at ideas.mozilla.org

prod-refractr.yml
Re [SE-3049](https://mozilla-hub.atlassian.net/browse/SE-3049)
Make sure the Netlify DNS part of above issue is completed before this is merged.
=> Remove surveillance.m.o

requirements.txt
=> Pin to older version of markupsafe

prod-refractr.yml
For our friends in the UK and Canada this could be a popular spelling
for our domain should they hear about it. Let's support them.
=> Add redirects for truecolours spellings

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SE-3083
Asked in ticket if having a TLS outage is acceptable.
https://mana.mozilla.org/wiki/display/SRE/Refractr+-+How+To+-+DNS+Challenges
=> chore(webxr): Redirect for webxr.today

prod-refractr.yml
Add www.webxr.today as well as webxr.today
=> chore(webxr.today): Also support www subdomain

prod-refractr.yml
The tests in the PR didn't pick this up? https://github.com/mozilla-it/refractr/pull/240
Tests pass locally now.
=> chore(trailing): Add a trailing slash for the tests

refractr/Dockerfile
JIRA ticket: [[SE-3096](https://mozilla-hub.atlassian.net/browse/SE-3096)]
=> Update nginx to get alpine-release 3.15.4

prod-refractr.yml
=> chore(truecolors): Truecolors campaign is phased out, redirect to

prod-refractr.yml
=> screenshots.firefox.com decommissioning SVCSE-449 SVCSE-741

prod-refractr.yml
=> task(refractr): Adding webvision redirect for SE-3300

prod-refractr.yml
=> task(refractr): Adding mdn-contributor-docs redirect for SE-3315

prod-refractr.yml
=> redirect mana.allizom.org to atlassian test instance

prod-refractr.yml
=> adding handling for mana.mozilla.org base url

prod-refractr.yml
=> Fix up getpulse domains

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SE-3415
=> feat: Redirect mixedreality.mozilla.org to hubs.m.c/labs/

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SE-3426
=> feature: Redirect design.firefox.com to acorn.firefox.com

prod-refractr.yml
add refracts for remote-settings GCP migration ([JIRA Ticket](https://mozilla-hub.atlassian.net/browse/OPST-305))
=> chore(remote-settings): add remote-settings dev redirect to gcp

prod-refractr.yml
=> chore: Redirect members.rally.mozilla.org to rally.mozilla.org

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SVCSE-1187?atlOrigin=eyJpIjoiYTYyYjgyZjBhNjk3NGIyNmI1OGZkODlhYzQwZTYyMzQiLCJwIjoiaiJ9
=> Adding redirect for mozilla-releng.net to docs.mozilla-releng.net

prod-refractr.yml
JIRA ticket: [OPST-277](https://mozilla-hub.atlassian.net/browse/OPST-277) + [MP-354](https://mozilla-hub.atlassian.net/browse/MP-354)
/cc @bkochendorfer
=> chore: redirect insights.developer.mozilla.org to mdn.dev

prod-refractr.yml
Test failure on publish:  https://github.com/mozilla-it/refractr/actions/runs/4951155032/jobs/8855748492
=> bug(perf-html.io): Fix up the test. I think this is correct

prod-refractr.yml
Also adds redirects from:
- media.prod.mdn.mozit.cloud
- media.stage.mdn.mozit.cloud
JIRA ticket: [MP-354](https://mozilla-hub.atlassian.net/browse/MP-354)
=> fix(mdn.dev): use regex to rewrite paths

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SVCSE-1316
=> Add SUMO redirects for fpn.firefox.com

prod-refractr.yml
JIRA ticket: [SE-3598](https://mozilla-hub.atlassian.net/browse/SE-3598)
=> Redirect help.getpocket.com to SUMO.

prod-refractr.yml
The blog post this links to will go live at 6am PDT.
JIRA ticket: [SE-3620](https://mozilla-hub.atlassian.net/browse/SE-3620)
=> Redirect rise25.mozilla.org to blog post.

prod-refractr.yml
Fix the schema from my last failed attempt to publish.
=> chore(schema): Fix schema for mdn redirects

prod-refractr.yml, requirements.txt
=> Adding redirect for Firefox Accounts

prod-refractr.yml
=> feat(pastebin): Redirect pastebin to mozgcp

prod-refractr.yml
=> fix fix fix

prod-refractr.yml
=> Added Monitor redirect to mozilla.org

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SE-3779
=> Redirect domain to mozilla org as the netlify site has been decommed

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SVCSE-1515
=> Removing redirect for services status page

prod-refractr.yml
JIRA ticket: [https://mozilla-hub.atlassian.net/browse/SVCSE-1515]
=> Redirects for VPN/Relay status pages

prod-refractr.yml
Fix relating to https://github.com/mozilla-it/refractr/pull/305
=> Fixing url redirect added trailing slash

prod-refractr.yml
see [SE-3622](https://mozilla-hub.atlassian.net/browse/SE-3622)
=> chore: drop rise25.mozilla.org redirect

prod-refractr.yml
=> removed_open.mozilla.org

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SE-3883
=> fix se-3883: add redirect for openwebgames.org

prod-refractr.yml
=> feat: adding redirect for llamafile.ai to github repo

prod-refractr.yml
=> SE-3911_cleanup:remove_foxfooding_redirect

prod-refractr.yml
=> feat(refractr): Add redirect for builders.mozilla.community

prod-refractr.yml
=> add redirect for jira.mozilla-community.org SE-4100

dodo.py, prod-refractr.yml
=> cleanup_stale_refracts_and_fix_typo_in_dodo_py

refractr/cfg.py
=> change_papertrail_to_any_working_value_refract_gcp_url_for_example

bin/create_certs.py, poetry.lock, pyproject.toml
=> chore: certificate creation script

prod-refractr.yml
=> chore(refractr):testrail.stage.mozaws.net redirect

prod-refractr.yml
=> observatory-stage-move

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/MP-1553
=> MDN Observatory prod move

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/DSRE-1793
=> DSRE-1793: Create URL redirect for Experimenter stage.

prod-refractr.yml
Follow up to https://github.com/mozilla-it/refractr/pull/367
=> DSRE-1793: Add missing trailing slash in destination.

prod-refractr.yml
JIRA ticket: [MP-1731](https://mozilla-hub.atlassian.net/browse/MP-1731)
=> chore(mdn): redirect test-de environment

prod-refractr.yml
=> Correcsyntax

prod-refractr.yml
typo
JIRA ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1944953
=> Bug 1944953: Update mozilla.it redirect, add utm parameters

prod-refractr.yml
=> chore: redirect mozilla-japan.org to mozilla.org/ja

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/MP-1892
=> chore(mdn): redirect old AWS dev environment

prod-refractr.yml
This refract was added for convenience early on in the Experimenter GCPv2 migration. It is no longer needed as the refracted domain was deleted when we cleaned up the GCPv1 project.
JIRA ticket: **None**
=> chore: Cleanup Experimenter refract

prod-refractr.yml
This is my first ever refractr PR, so I am expecting there to be issues. Please don't hold back.
When creating a PR for Refractr, confirm you've done the following steps for a smooth CI and CD experience:
=> (feat) OPST-2429: Redirects from future.m.o to newproducts.m.o

prod-refractr.yml
When creating a PR for Refractr, confirm you've done the following steps for a smooth CI and CD experience:
=> chore(OPST-2535): add part-infra redirects

prod-refractr.yml
When creating a PR for Refractr, confirm you've done the following steps for a smooth CI and CD experience:
=> chore(refractr): translate.firefox.com
