mozilla-it/refractr

README.md
This pull request adds a Travis CI build badge to provide an indication of the "build-ability" of the master branch on the README page of the repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-it/refractr/13)
=> Travis CI, master branch status on README

.pre-commit-config.yaml, .secrets.baseline
This pull request (PR) provides a set of initial pre-commit hooks.  The initial set of hooks adds support for:
- [Yelp's detect secrets hook](https://github.com/Yelp/detect-secrets)
- Out of the box checks for large files, trailing line, etc
No code formatters were added outside of the trailing line hook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-it/refractr/14)
=> Initial pre-commit hooks

.travis.yml, dodo.py
Rework travis logic, it was previously trying to push an image on every branch created and every push to the repo. Now there is a deploy section which checks and only publishes an image if its on branch master or branch prod.
Note that the image names are still all going to be the same and there is no logic to split out the names of the docker builds based on branches yet
=> Rework travis logic

bin/refractr, refractr/base.py, refractr/complex.py, refractr/refractr.py, refractr/simple.py, refractr/url.py, refractr/utils.py, requirements.txt
- made sure dsts, srcs and tests are stored as tuples
- bumped leatherman.fuzzy to v0.0.10 to sort on list of lists
- used improved leatherman.fuzzy searching to improve matches on patterns
- added --all-sources option to pattern matches, but first server_name
the default
- broke out generate_tests for Single and Complex Refracts
=> improve the fuzzy include search results

dodo.py, refractr/cfg.py
- moved task bodies that require creds into python function
- this allows these evaluations to happen ondemand (lazy)
- this allows doit list and many of the tasks to run without creds
=> lazy eval to help doit tasks and load

refractr/ingress.yaml.template
Update `ingress` object `apiVersion`, since kubernetes 1.16 the api `extentions/v1beta1` has been removed so  we're switching over to the new api
See: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
=> Update ingress apiVersion

prod-refractr.yml, prod-refractr.yml.bak
- join.mozilla.org
- hub.mozilla.{com,org}
- thehub.mozilla.org
- cleopatra.io
- treestatus.mozilla.org
- extensiontest.com
- [www.]mozilla.org.uk
- triagebot.mozilla.org
=> moved 10 more low risk domains to refractr

prod-refractr.yml, refractr/base.py, refractr/complex.py, refractr/refractr.py, refractr/schema.yml, refractr/simple.py, refractr/url.py, tests/test_refractr.py
- nginx doesnt preserve the path during redirect like Apache does
- added 'preserve_path' boolean option for simple and complex refracts
- changed schema to allow this new field
- wired nginx generation code to replace '/' with $request_uri if
toggled
- wired test generation code to add '/path' per domain if toggled
=> added preserve_path feature for firefox.com

prod-refractr.yml
This should redirect all traffic going to mozillians.org/* to people.mozilla.org/
=> Redirect mozillians.org to people.mozilla.org/

prod-refractr.yml
=> Redirect send.firefox.com to www.mozilla.org

prod-refractr.yml
=> Redirect testpilot.firefox.com to fpn.firefox.com

prod-refractr.yml
Reported in this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1666460, we want to update the redirection to the new URL, saving one hop
=> Update redirection to new URL; Saves 1 hop

prod-refractr.yml
mozilla-hispano.org to https://community.mozilla.org/es/groups/mozilla-hispano/
mozillavenezuela.org to https://community.mozilla.org/es/groups/mozilla-venezuela/
https://bugzilla.mozilla.org/show_bug.cgi?id=1697571
https://bugzilla.mozilla.org/show_bug.cgi?id=1697638
=> Add mozilla-hispano.org and mozillavenezuela.org

prod-refractr.yml
The DNS response for this domain is used to test if DoH should be
enabled or not. We're setting up a redirect in case someone is curious
and tries to access it in their browser. For more details, see
https://jira.mozilla.com/browse/SE-1564
This is being migrated from the datacenter redirects cluster to
refractr.
=> Add use-application-dns.net

prod-refractr.yml
We missed this when doing the redirects earlier.
=> Redirect foro.mozilla-hispano.org to discourse

refractr/cfg.py
Without this, only annotated tags are considered when generating the
name to tag the docker image with.
=> Support releases that use lightweight tags

prod-refractr.yml
It was failing tests because it looks like it was being associated with the
redirect above, breaking the tests.
=> Moving this config value out a block

prod-refractr.yml
This is now going straight to Github.
https://bugzilla.mozilla.org/show_bug.cgi?id=1702294
=> Remove spidermonkey.dev

prod-refractr.yml
This was requested in https://jira.mozilla.com/browse/SE-1651
I have already configured DNS
```
$ host ideas.mozilla.org
ideas.mozilla.org is an alias for prod.refractr.mozit.cloud.
```
=> Redirect ideas.mozilla.org to crowdicity

prod-refractr.yml
See https://jira.mozilla.com/browse/SE-1682
Checklist:
=> remove extranet.mozilla.org to mozilla.grouphub.com redirect

prod-refractr.yml
JIRA ticket: https://jira.mozilla.com/browse/SE-1683
=> adding addons.mozilla.com -> addons.mozilla.org rewrite

prod-refractr.yml
What this PR does: Redirect inhumanads.com to www.mozilla.org
JIRA ticket: https://jira.mozilla.com/browse/SE-1224
=> redirect InHumanAds.com to www.mozilla.org

prod-refractr.yml
JIRA ticket: https://jira.mozilla.com/browse/SE-1862
Note: gcox found a list of domains needing to be mapped over to refractr. See ticket for list. Added domain plus www.domain given some looking at what infoblox records exist now.
=> add list of domains identified by gcox to redirect to firefox

requirements.txt
This fixes the dependabot warnings shown on the repo page, and also cleans up the requirements file a bit.
* `black` and `pyyaml` are unused in the whole code base, so I removed them.
* Minor version upgrades for `aiohttp` and `jinja2` to fix dependabot warnings. I read the changelog and ran the tests to make sure this doesn't break anything.
* Fix `idna` version. This package isn't directly needed by the code in this repository. It's a transitive dependency via multiple paths, though, and pip does not resolve the version correctly if we don't specify it here.
I'll file issues for a few further improvements I'd suggest on Jira.
=> Update and clean up dependencies.

prod-refractr.yml
JIRA ticket: https://jira.mozilla.com/browse/SE-1571?focusedCommentId=276689&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-276689 (see specific comment re: 302)
=> make developer.cdn.mozilla.net redirect return 302

README.md, stage-refractr.yml
Confirming stage deploy okay after out-of-band, ingress-nginx helm-managed ValidatingWebHookConfiguration resource removed from test namespace work.
=> comment out stage domains that dont point to refractr

prod-refractr.yml
JIRA ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1617378
=> repair www.mozillians.org lack of cert / bad CNAME

prod-refractr.yml
This is a request we received through [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1660250).
techspeakers.mozilla.org currently resolves to refractr but 404s. This will redirect the url to the community portal.
```sh
server {
server_name techspeakers.mozilla.org;
add_header Strict-Transport-Security "max-age=60; includeSubDomains"
always;
location = / {
return 301
https://community.mozilla.org/en/groups/tech-speakers/;
}
}
```
Looks like other  refractrs are pointing to community.mozilla.org so I think that should be okay. It isn't controlled by refractr.
Yep, shown above.
Definitely.
After PR merge, next steps …
=> Redirect techspeakers to community portal

prod-refractr.yml
Based on https://bugzilla.mozilla.org/show_bug.cgi?id=1598043 I believe we can now redirect www.mozilla.ch to mozilla.org. DNS is already pointing at refractr. The `www` subdomain currently 404s. Certificate offered from the `www` subdomain is a generic k8s ingress certificate.
JIRA ticket: [https://mozilla-hub.atlassian.net/browse/SE-2237]
Hopefully.
DNS already pointed at refractr and the subdomain `www.` 404s. Any outage for certificate here should be fine as it is not working right now.
I generated the config and looked at it. It looks correct to me.
Yes, I certainly can
DNS is already created and pointing at refractr.
=> SE-2237 Redirect for www.mozilla.ch

.github/pull_request_template.md, prod-refractr.yml
JIRA ticket: SE-2238, https://bugzilla.mozilla.org/show_bug.cgi?id=1660250
Note: PR repairs techspeakers.mozilla.org being redirected twice, plus missing other redirect request in bugzilla ticket (developer.mozilla.com/communities/mozilla-tech-speakers)
=> techspeakers.mozilla.org redirected twice

.github/pull_request_template.md, prod-refractr.yml
JIRA ticket: SE-2238 repair 2, bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1660250
Note: PR adds note for MDN-managed redirects to PR checklist
=> add note for MDN-managed redirects

prod-refractr.yml, refractr/schema.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SE-2412
Just pushing this work up in case useful & to clear my local git for refractr. It was the way I found last week to add the personas.com regex matching paths redirect to refractr without changing refractr python classes (does require updating the refractr schema though). Happy to pair on reviewing it, again, if useful to have.
=> getpersonas.com & www.getpersonas.com paths rewrites

prod-refractr.yml
This adds the redirect for / that was missing in #195. Unfortuantely, simply adding the redirect broke one of the other redirects, for reasons I can't explain. I changed the other redirects to the form we use for getpersonas.com, and now it seems to be working.
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SE-2241
=> Add missing redirect for https://bugzil.la/.

prod-refractr.yml
JIRA ticket: [SE-2712](https://mozilla-hub.atlassian.net/browse/SE-2712)
=> Remove trailing slashes from four Wikimo redirects [SE-2712]

prod-refractr.yml
This should enable us to decom the meao based deployment entirely
This PR makes some small changes to current behavior
Picking 302 for most of the redirects
Adding a fallback behavior as well
=> Moving www.firefox.com redirects to refractr

prod-refractr.yml
Due to using a subpath for the moz.org careers page, preserve path option is disabled.
These paths will fix the few items we care about from the old page
=> Careers Listing and Feed Pages now redirect

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/DSRE-493
=> redirect status.services.mozilla.com to www.mozilla.org

prod-refractr.yml, refractr/schema.yml
The turningred.firefox.com domain will need to be created and pointed to Refractr.
Fix [SE-3052](https://mozilla-hub.atlassian.net/browse/SE-3052)
=> Add redirects for firefox.com/turningred and turningred.firefox.com

prod-refractr.yml
For some reason the www redirect goes to www.moz.org instead of redirecting correctly to support
=> chore(webxr.today): Update to redirect directly to support. 

stage-refractr.yml
As discussed in the team meeting, these domain names don't resolve and result in some error in stage Refratctr.
I also [pinged Dustin](https://mozilla-hub.atlassian.net/browse/SVCSE-350?focusedCommentId=535161) about moving his redirect to the prod instance, but I'll do that in a separate PR.
=> Remove domains that don't resolve from the stage config.

prod-refractr.yml
We want to point the root at a cloudfront distribution which we cannot do because the root is in infoblox. This is the same behavior as mozilla.org. Point the A record at refractr point a www cname at cloudfront
=> chore(redirect): tekcopteg.com to www.tekcopteg.com

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/DSRE-975
=> Remove reports.telemetry.mozilla.org redirect

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/DSRE-671
I had just asked :gcox to delete DNS for this entirely yesterday but there was enough desire to have a redirect that we'd like one. Once this lands I will ask gcox to update DNS, but I'm not too familiar with the deployment process.
=> Add missioncontrol.telemetry.mozilla.org redirect

prod-refractr.yml, refractr/base.py, refractr/schema.yml
adding refract for specific mana page linked from pto.m.o updated schema to accomodate dst urls that include '+'
=> Added workaround for trailing '?'

prod-refractr.yml
WPENGINE (blog.m.o) does not cache utm_source. This is contributing to increased utilization.
=> Remove utm_source as it is not cached by wpengine

prod-refractr.yml
This is a common problem in many of the refractr setups. We unintentionally duplicate request parameters.
Old generated configuration:
```bash
server {                                                                        
server_name mozilla.org;                                                    
add_header Strict-Transport-Security "max-age=60; includeSubDomains" always;
add_header X-Backend-Server TS;                                             
add_header Cache-Control max-age=3600;                                      
location = /.well-known/matrix/client {                                     
add_header Access-Control-Allow-Origin '*';                             
add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS';
add_header Access-Control-Allow-Headers …
```
=> chore(bedrock): Do not duplicate parameters

prod-refractr.yml
Implements https://bugzilla.mozilla.org/show_bug.cgi?id=1804734. Not sure where `perf-html.io` lives but I'll need to get access to update that.
=> chore(perf-html): I cannot get the tests to run locally so here we are

prod-refractr.yml
This is kind of interesting! The regular quotes are put into the nginx config but are not sent to the client. In this particular header if the string isn't wrapped in a double quote it is [considered invalid](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data?utm_source=mozilla&utm_medium=devtools-netmonitor&utm_campaign=default).
This plops the escape into the nginx config:
```bash
add_header Clear-Site-Data \"storage\";
```
And I confirmed locally that the quote is returned via curl:
```bash
$ curl -i -L --header 'Host: perf-html.io' localhost
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Fri, 12 May 2023 14:48:34 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://profiler.firefox.com/
Strict-Transport-Security: …
```
=> chore(perf-html): Force quoted header

prod-refractr.yml
Fixup for #288.
JIRA ticket: [SE-3598](https://mozilla-hub.atlassian.net/browse/SE-3598)
=> Fix help.getpocket.com redirect.

prod-refractr.yml
Fix up for #290. Apparently, the redirect target must not include "https://".
For some reason, CI was successful for the PR and after merging to main, and only failed once I tagged a release. We should make sure the tests run on the PR branch as well; it would be really nice to catch this before merging the PR and tagging a release.
=> Fix up for rise25 redirect.

.github/pull_request_template.md, prod-refractr.yml
JIRA ticket: [SE-3660](https://mozilla-hub.atlassian.net/browse/SE-3660)
Or I could create the redirects using the Gateway API in Kubernetes. This seems like the logical place, I'm not sure why it didn't exist over here already.
=> chore(mdn): Migrate the mdn redirector service over to refractr

prod-refractr.yml
Previous publish failed at running the tests. I forgot that we don't run the actual tests until then. https://github.com/mozilla-it/refractr/actions/runs/6565153588 I was able to get the test running locally with the help of `asdf`, they only run on python 3.7.
=> fix(mdn): Redirects

prod-refractr.yml
(For 2024, marking as draft)
JIRA ticket: https://mozilla-hub.atlassian.net/browse/DSRE-1173
=> chore: redirect rally domains to www.mozilla.org

prod-refractr.yml
We're going to be transferring the domain mozilla.tw in to markmonitor.  The only thing it's doing is a courtesy redirect to a community site on another domain.
We'd like refractr to take on that redirect.   ~~We don't have the domain yet, and we understand things will be a little kerfuffled while we get control of the domain in Markmonitor, but we wanted to get the PR on file in parallel~~  [28Feb] We have the domain in Markmonitor now.
JIRA ticket: [IO-2668](https://mozilla-hub.atlassian.net/browse/IO-2668)
=> Add redirect for mozilla.tw / moztw.org, IO-2668

prod-refractr.yml
This already exists as a target, so I've added `games.mozilla.org` to the existing list and appended the ticket to the existing comment
---
=> fix se-3899: redirect games.mozilla.org to developer.mozilla.org/en-US/docs/Games/

prod-refractr.yml
JIRA ticket: [MP-1163](https://mozilla-hub.atlassian.net/browse/MP-1163)
=> fix: redirect developer.cdn.mozilla.net permanently

prod-refractr.yml
JIRA ticket: https://mozilla-hub.atlassian.net/browse/SVCSE-1946
=> fix: redirect hubs.mozilla.com to sumo article

prod-refractr.yml
Some links on these domains appeared on Google. The CNAME entries are already made in AWS Route 53.
JIRA ticket: https://mozilla-hub.atlassian.net/browse/MP-1238
=> chore: redirect yari-demos.{prod,stage}.mdn.mozit.cloud -> developer.mozilla.org

stage-refractr.yml
=> removing_default_domains_refractr_stage
